language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
before_install:
  - "pip install --user conan"
  - "conan remote add joystream https://conan.joystream.co:9300 True"
  - "conan user travis -p trav444 -r=joystream"
