language: node_js

node_js:
  - "7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode7.3
      sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
  apt:
    packages:
    - fakeroot

before_install:
  - if [[ "$TRAVIS_OS_NAME" = osx ]]; then
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
      ruby --version;
      brew install python@2;
      export PATH="/usr/local/opt/python@2/libexec/bin:$PATH";
      export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH";
      python -m pip install --upgrade --force pip setuptools;
    fi
  # Install conan
  - if [ "$TRAVIS_OS_NAME" = osx ]; then
      python -m pip install "conan==0.28.1";
      python -m pip uninstall pyopenssl;
      python -m pip uninstall cryptography;
      python -m pip install "pyopenssl>=16.0.0, <17.0.0";
    else
      pip install --user "conan==0.28.1";
    fi
  - conan remote add joystream https://api.bintray.com/conan/joystream/joystream True

install:

script:
  - npm install
  - npm test
