dist: trusty
sudo: false
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then pip install conan; else pip install --user conan; fi
  - "conan remote add joystream https://api.bintray.com/conan/joystream/joystream True"
